# Generated by Django 3.2.8 on 2021-10-16 00:54

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generateCode, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_control', models.BooleanField(default=False)),
                ('video_id', models.CharField(default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 16, 7, 54, 31, 213303), serialize=False)),
            ],
        ),
    ]
