# Generated by Django 3.2.8 on 2021-10-16 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 7, 56, 16, 297322), serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
