# Generated by Django 3.2.8 on 2021-10-16 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211016_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video_status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 8, 9, 23, 673654), serialize=False),
        ),
    ]
