# Generated by Django 3.2.8 on 2021-10-16 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211016_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video_current_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='video_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 8, 13, 14, 919742), serialize=False),
        ),
    ]
