# Generated by Django 3.2.8 on 2021-10-16 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211016_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 10, 29, 22, 205870), serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_current_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_status',
            field=models.IntegerField(default=-1),
        ),
    ]
